# Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.

# 基础配置
[base]
name = "yolox_post"                          # 功能单元名称
device = "cpu"                               # 功能单元运行的设备类型，Python功能单元仅支持cpu类型
version = "1.0.0"                            # 功能单元版本号
type = "python"                              # 功能单元类型，Python功能单元此处为固定值python
group_type = "generic"                       # 功能单元分组信息, 包括input/output/image/video/inference/generic等，默认为generic
description = "post-process for yolox model" # 功能单元的功能描述信息
entry = "yolox_post@yolox_postFlowUnit"      # Python功能单元入口

# 工作模式，以下配置项默认全为false，表示通用功能单元；且配置项之间互斥，即最多只能设置其中一个为true
stream = false    # 是否是Stream类型功能单元
condition = false # 是否是条件功能单元
collapse = false  # 是否是合并功能单元
expand = false    # 是否是展开功能单元

# 自定义的配置项：yolox模型后处理需要的参数
[config]
net_h = 320
net_w = 320
num_classes = 2
strides = ['8', '16', '32']
conf_threshold = 0.6
iou_threshold = 0.4

# 输入端口描述
[input]
[input.input1] # 输入数据
name = "in_feat" # yolox模型的特征向量输出
type = "float"   # 特征向量数据类型为 float

# 输出端口描述
[output]
[output.output1] # 输出数据
name = "out_data" # 检测框数据
type = "string"   # 检测框数据格式为json字符串